version: "3.7"

services:
  test:
    build:
      context: .
      target: test
    depends_on:
      - postgres
    command: bash -c 'chmod +x ./wait-for-it.sh && ./wait-for-it.sh postgres:5432 redis:6379 -- yarn test'
  postgres:
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_USER: "${TEST_DB_USER}"
      POSTGRES_PASSWORD: "${TEST_DB_PW}"
      POSTGRES_DB: "${TEST_DB_NAME}"
  redis:
    image: redis:latest
    ports:
      - 6378:6379
