version: "3.7"

services:
  test:
    build:
      context: .
      target: test
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_USER: "${TEST_DB_USER}"
      POSTGRES_PASSWORD: "${TEST_DB_PW}"
      POSTGRES_DB: "${TEST_DB_NAME}"
