version: "3.7"

services:
    dev:
        image: node:latest
        command: bash -c '
            apt-get update &&
            apt-get install -y netcat &&
            chmod +x ./wait-for-it.sh &&
            ./wait-for-it.sh postgres:5432 -- yarn migration-run &&
            yarn dev'
        ports:
            - 3000:3000
            - 5000:5000
        working_dir: /app
        volumes:
            - ./:/app
        depends_on:
            - postgres
    postgres:
        image: postgres:latest
        volumes:
            - tutor-timetable-postgres:/var/lib/postgresql/data
        restart: always
#        ports:
#            - 5431:5432
        env_file: .env
        environment:
            POSTGRES_USER: "${DB_USER}"
            POSTGRES_PASSWORD: "${DB_PW}"
            POSTGRES_DB: "${DB_NAME}"
#    postgres-seed:


volumes:
    tutor-timetable-postgres:
