version: "3.7"

services:
    dev:
        build:
            context: .
            target: dev
        ports:
            - 3000:3000
            - 5000:5000
        volumes:
            - ./:/app
        depends_on:
            - postgres
    postgres:
        image: postgres:latest
        volumes:
            - tutor-timetable-postgres:/var/lib/postgresql/data
            - ./bootstrap/data:/docker-entrypoint-initdb.d
        restart: always
        ports:
            - 5431:5432
        env_file: .env
        environment:
            POSTGRES_USER: "${DB_USER}"
            POSTGRES_PASSWORD: "${DB_PW}"
            POSTGRES_DB: "${DB_NAME}"

volumes:
    tutor-timetable-postgres:
