version: "3.7"

services:
    dev:
        image: node:latest
        command: "cp .env.docker .env && ./wait-for postgres:5431 -- yarn dev"
        ports:
            - 3000:3000
            - 5000:5000
        working_dir: /app
        volumes:
            - ./:/app
#        env_file: .env.docker
        depends_on:
            - postgres
    postgres:
        image: postgres:latest
        volumes:
            - tutor-timetable-postgres:/var/lib/postgresql/data
        restart: always
        ports:
            - 5431:5432
        environment:

#    postgres-seed:


volumes:
    tutor-timetable-postgres:
